### ISSUE TITLE
Query about the API source

### ISSUE THREAD

**Issue by IanVermes** [karina4840/elasticsearch-test-api#1]
https://github.com/karina4840/elasticsearch-test-api/blob/34854ace1067d1361f9ba8d4db9e8ed0340c577e/src/Components/App.jsx#L17

Would you be kind enough to explain the origin of this GCP API endpoint?  What was the reason not to use `http://cosmic-elastic.eu.ngrok.io/shakespeare/_search?` ?

**Comment by karina4840** [comment]
Hi Ian, 
I have never worked with Elasticsearch and I couldn't figure out how to connect the end point that was provided in React. According to the docs, you need to provide credentials for connecting the API which I didn't have, so I found the .json file and uploaded it to the engine.

**Comment by IanVermes** [comment]
Thank you
